### ISSUE TITLE
TTS not reading more than the 1st item in a list

### ISSUE THREAD

**Issue by MikeStirner** [SheikhAminul/ChatGPT-voice-control#4]
When using TTS, if chatGPT makes a numbered list, only the first item on the list is read aloud. Then it reads the text after the end of list (if there is more text after the list). It should read all the items in the list.

Using Chrome, Windows 10 Pro. Both up to date.

**Comment by MikeStirner** [comment]
It happens when the 1st item in the list contains more than one sentence and is followed by a 2nd list item.

**Comment by SheikhAminul** [comment]
Hi @MikeStirner 
I updated the extension. The new version is currently under review.
The issue will be fixed as soon as Google approves the new version.
Thank you.

**Comment by SheikhAminul** [comment]
Hi @MikeStirner 
I updated the extension. The new version is currently under review.
The issue will be fixed as soon as Google approves the new version.
Thank you.
